Part 14 external api
the-action-man/tn-test-guru pull request #23
Opened 2020-10-02 16:22 UTC by the-action-man

2020-12-04 08:03 UTC, VidgarVii requested changes

2020-12-04 08:03 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    @client = client || GitHubClient.new
вот тут бы явно и подключил клиента октокит.. А создание объекта клиента положил бы в приват метод

2020-12-04 08:03 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    # @client = client
отладочный код следует убирать

2020-12-04 08:03 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  end
эту логику лучше инкапсулировать в сервис.

2020-12-04 10:03 UTC, the-action-man commented on app/controllers/test_passages_controller.rb
> +  end
Перенес.
Спасибо!

2020-12-04 10:03 UTC, the-action-man commented on app/services/gist_question_service.rb
> +    @client = client || GitHubClient.new
Так и сделал.
Спасибо!

2020-12-04 10:04 UTC, the-action-man commented on app/services/gist_question_service.rb
> +    # @client = client
Убрал.
Спасибо!

2020-12-04 10:04 UTC, the-action-man commented on app/controllers/test_passages_controller.rb
> +  end
Перенес.
Спасибо!

2020-12-04 13:47 UTC, VidgarVii commented on app/helpers/gists_helper.rb
> +    text[0..25]
есть готовый хелпер truncate

2020-12-04 13:47 UTC, VidgarVii commented on app/views/admin/gists/_gist.html.erb
> +    <a href="<%= gist.url %>"><%= url_hash(gist.url) %></a>
link_to

2020-12-04 13:47 UTC, VidgarVii commented on app/views/admin/gists/_gist.html.erb
> +    <a href="<%= admin_question_path(gist.question.id) %>">
link_to

2020-12-05 15:42 UTC, the-action-man commented on app/helpers/gists_helper.rb
> +    text[0..25]
Круто!
Спасибо!

2020-12-05 15:55 UTC, the-action-man commented on app/views/admin/gists/_gist.html.erb
> +    <a href="<%= gist.url %>"><%= url_hash(gist.url) %></a>
исправил

2020-12-05 15:55 UTC, the-action-man commented on app/views/admin/gists/_gist.html.erb
> +    <a href="<%= admin_question_path(gist.question.id) %>">
исправил

2020-12-05 16:01 UTC, merged