Part 15 java script
the-action-man/tn-test-guru pull request #26
Opened 2020-12-05 20:09 UTC by the-action-man

<img width="969" alt="изображение" src="https://user-images.githubusercontent.com/49880822/101262329-e2fadc00-374e-11eb-861c-968ca2374bd1.png">

2020-12-06 13:03 UTC, VidgarVii requested changes

2020-12-06 13:03 UTC, VidgarVii commented on app/assets/javascripts/devise/registrations/new.js
> +  if(passConfirm) { passConfirm.addEventListener('input', verifyPasswordConfirmation); }
if (user_password_confirmation) enablePasswordHandler(user_password_confirmation)

2020-12-06 17:27 UTC, the-action-man commented on app/assets/javascripts/devise/registrations/new.js
> +  var pass = document.querySelector("#user_password").value;
Исправил
Спасибо!

2020-12-06 17:36 UTC, the-action-man commented on app/assets/javascripts/devise/registrations/new.js
> +}
Исправил
Спасибо!

2020-12-06 17:42 UTC, the-action-man commented on app/assets/javascripts/devise/registrations/new.js
> +  if(passConfirm) { passConfirm.addEventListener('input', verifyPasswordConfirmation); }
Исправил
Спасибо!

2020-12-06 18:02 UTC, the-action-man commented on app/assets/javascripts/devise/registrations/new.js
> +  var alert = document.querySelector('.octicon-alert');
Добавил айди для иконки

2020-12-06 18:58 UTC, the-action-man commented on app/assets/javascripts/utilities/sorting.js
> +  }
done

2020-12-06 21:15 UTC, the-action-man commented on app/assets/javascripts/utilities/sorting.js
> +}
1
Код полностью слизан из примера в видео перед заданием. На сколько я погуглил и  понял у ДжаваСкипта есть свои вкусности и стилистика програминга. Однако на сколько я понял гугл - это огромная тема и в рамках этого одного урока мы никак это не поднимем?

2
переименовал паку в table

2020-12-06 21:16 UTC, the-action-man commented on app/assets/javascripts/utilities/sorting.js
> +}
Код полностью слизан из примера в видео перед заданием. 
Поэтому не понимаю о чем речь.

2020-12-06 21:39 UTC, the-action-man commented on app/assets/stylesheets/application.scss
> +@import "global";
1
"В старых ПР ты затер подключение файлов через = require_" (с)
Не понимаю о чем речь. Я посмотрел историю фала... вроде ничего нигде не удалалось

2
"CDN в application.html"
2.1
раскрой тему 
покажи пример кода что как и почему
2.2
кинь ссылку почитать что такое вообще CDN

2020-12-08 07:31 UTC, VidgarVii requested changes

2020-12-08 07:31 UTC, VidgarVii commented on app/assets/javascripts/table/sorting.js
> +    return table.querySelectorAll('tr');
увеличение абстракций  не решает проблему кол-ва абстракций.
Эти 2 функции убивают понимание кода

2020-12-08 17:31 UTC, the-action-man commented on app/assets/javascripts/table/sorting.js
> +    var control = document.querySelector('.sort-by-title');
Добавил.
Спасибо!

2020-12-08 17:36 UTC, the-action-man commented on app/assets/javascripts/table/sorting.js
> +    var control = document.querySelector('.sort-by-title');
поменял на let
переименовал в titleColumnHeader

2020-12-08 19:23 UTC, the-action-man commented on app/assets/javascripts/table/sorting.js
> +    if(control) { control.addEventListener('click', sortRowsByTitle); }
Да, извиняюсь за скобки. Несколько раз переделывал и где-то опять упустил.

Добавил ESLint который проверяет JavaScript Standard Style

2020-12-08 19:45 UTC, the-action-man commented on app/assets/stylesheets/application.scss
> +@import "global";
добавил

2020-12-08 19:48 UTC, the-action-man commented on app/assets/javascripts/table/sorting.js
> +    return table.querySelectorAll('tr');
убрал

2020-12-08 20:03 UTC, the-action-man commented on app/views/admin/tests/index.html.erb
> +      <%= octicon 'arrow-down', id: "octicon_title_arrow_down", class: 'text-success' %>
Исправил
Спасибо!

2020-12-09 09:17 UTC, merged