Part 17 deploy final
the-action-man/tn-test-guru pull request #30
Opened 2020-12-18 21:29 UTC by the-action-man

<img width="830" alt="изображение" src="https://user-images.githubusercontent.com/49880822/102663155-4f370000-4191-11eb-930d-81fd06ac7959.png">

2020-12-20 09:36 UTC, VidgarVii requested changes

2020-12-20 09:36 UTC, VidgarVii commented on .env
> +GITHUB_TOKEN=e4fc38a41a30268dcdcd5796333b583e77052074
такие данные не должны лежать в открытом доступе!

2020-12-20 09:36 UTC, VidgarVii commented on db/seeds.rb
> +# password = '123456'
забавный момент, что пароли совпадают =)

2020-12-20 09:36 UTC, VidgarVii commented on db/migrate/20191024220449_remove_test_from_answers.rb
> +    # remove_column :answers, :test_id, :integer
зачем нам такая миграция?

2020-12-20 09:36 UTC, VidgarVii commented on app/views/layouts/_nav.html.erb
>    <tr>
_nav это не layout

2020-12-20 09:36 UTC, VidgarVii commented on app/models/support_message.rb
> +            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
есть готовый проверенный формат URI::MailTo::EMAIL_REGEXP

2020-12-20 09:36 UTC, VidgarVii commented on app/models/support_message.rb
> +class SupportMessage < ApplicationRecord
а зачем нам вообще хранить в базе сообщения? Да и всё ровно нет реализации, чтобы посмотреть все сообщения через админку

2020-12-20 09:36 UTC, VidgarVii commented on app/mailers/support_message_mailer.rb
> +    User.admins.pluck(:email)
Admin.pluck(:email)

2020-12-20 09:36 UTC, VidgarVii commented on app/controllers/support_messages_controller.rb
> +      redirect_to root_path, notice: "The message is sent to administrator!"
весь контент должен лежать в файлах локали

2020-12-20 14:07 UTC, the-action-man commented on app/models/support_message.rb
> +class SupportMessage < ApplicationRecord
"а зачем нам вообще хранить в базе сообщения?" (с)
1) Если вдруг глюкнет рассылка письма и сообщени от клиента не дойдет до админа, то можно будет в БД все посмотреть. Информация от клиента - это важно.
"Да и всё ровно нет реализации, чтобы посмотреть все сообщения через админку" (с)
2) За деньги заказчика реализуем любой каприз. Пока месть такого запроса не поступало. :)

2020-12-20 18:23 UTC, the-action-man commented on .env
> +GITHUB_TOKEN=e4fc38a41a30268dcdcd5796333b583e77052074
Убрал
Спасибо!

2020-12-20 18:28 UTC, the-action-man commented on app/models/support_message.rb
> +            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
Исправил
Спасибо!

2020-12-20 19:00 UTC, the-action-man commented on app/mailers/support_message_mailer.rb
> +    User.admins.pluck(:email)
Заменил
Спасибо!

2020-12-20 19:39 UTC, the-action-man commented on app/controllers/support_messages_controller.rb
> +      redirect_to root_path, notice: "The message is sent to administrator!"
сделал

2020-12-22 18:30 UTC, the-action-man commented on db/migrate/20191024220449_remove_test_from_answers.rb
> +    # remove_column :answers, :test_id, :integer
removed
thanks!

2020-12-22 18:37 UTC, the-action-man commented on app/views/layouts/_nav.html.erb
>    <tr>
Я не знаю куда _nav можно/нужно перенести...
На сколько я понимаю layout - это нечто общее для всех страниц. Меню навигации вроде как общее?

2020-12-25 21:22 UTC, merged