Part 18 feature 1 badges v2
the-action-man/tn-test-guru pull request #32
Opened 2021-03-12 19:04 UTC by the-action-man

<img width="840" alt="изображение" src="https://user-images.githubusercontent.com/49880822/110986571-e2419980-837e-11eb-80e4-6652a375e9ac.png">

2021-03-16 06:22 UTC, VidgarVii requested changes

2021-03-16 06:22 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      redirect_to result_test_passage_path(@test_passage, badges: BadgeService.new(@test_passage).call)
не очень понятно решение.
Совсем не очевидно что метод call возвращает ид баджей. Тогда надо метод назвать корректно.
На страницу result юзер может попасть в любое время. А с не очевидным параметром badges данный функционал сломан

Есть BadgesController где можно посмотреть список наград. Это достаточно
Если хочешь выводить список новых полученных наград используй flash

2021-03-16 06:22 UTC, VidgarVii commented on app/models/rule.rb
> +end
по моему этот класс не используется

2021-03-16 06:22 UTC, VidgarVii commented on app/models/badge.rb
> +end
1 не хватает валидаций. По ДЗ Админ может создавать баджи. Значит входящие данные надо бы валидировать
2 связь не корректна. Нет user_badges

2021-03-16 06:22 UTC, VidgarVii commented on app/services/badge_service.rb
> +        user_badge.count += 1
Лучшее не просто count а в названии уточнить что это за счётчик. А то можно подумать вызываешь рельсовый метод класс не там где надо.
Узнать кол-во наград, можно простым sql запросам. Императивно каждый раз считать не надо.

Если хочешь за кешировать счётчик (что вполне оправдано), то в рельсе уже есть готовая реализация http://rusrails.ru/active-record-associations#counter_cache

2021-03-16 06:22 UTC, VidgarVii commented on app/services/badge_service.rb
> +      @badges << badge if rule.satisfied?
можно сократить код написав сразу
```
@user.badges.push(badge) if rule.satisfied?
```

2021-03-16 06:22 UTC, VidgarVii commented on app/specifications/badges/elementary_of_category.rb
> +    end
последние 2 строчки вполне можно заменить на 
```
(test_passages.keys - test_ids).size.negative?
```
только надо протестить корректно ли работает данное правило

2021-03-16 06:37 UTC, the-action-man commented on app/services/badge_service.rb
> +      @badges << badge if rule.satisfied?
Не подходит в данном случае. Ниже есть подобное.
https://github.com/the-action-man/tn-test-guru/pull/32/files/ab7d2ab4f8dc0786822aaf443e72a4ec7f1d26e7#diff-e61ff5394fb1ea204ae7c36ffe8ba00db8ceb1e14a2e919f24e41a53c66a7410R53
Но нужно же еще и счетчик обработать счетчик. На пару строк выше это находится.

2021-03-16 09:12 UTC, the-action-man commented on app/models/rule.rb
> +end
removed

2021-03-16 09:16 UTC, the-action-man commented on app/specifications/badges/elementary_of_category.rb
> +    end
I used `(test_passages.keys - test_ids).size.zero?`

2021-03-16 10:33 UTC, the-action-man commented on app/models/badge.rb
> +end
1
added
2
`has_many :user_badges, dependent: :destroy` was added

2021-03-16 10:46 UTC, the-action-man commented on app/services/badge_service.rb
> +        user_badge.count += 1
renamed to quantity

2021-03-16 10:54 UTC, the-action-man commented on app/controllers/test_passages_controller.rb
> +      redirect_to result_test_passage_path(@test_passage, badges: BadgeService.new(@test_passage).call)
Удалил отображение полученных бейджей на странице result

2021-03-16 13:02 UTC, VidgarVii requested changes

2021-03-16 13:02 UTC, VidgarVii commented on app/services/badge_service.rb
> +  end
1 Если использовать enum для правил, то этот метод будет не нужен
2 Так же тут нарушается принцип единственной ответственности

2021-03-16 13:02 UTC, VidgarVii commented on app/services/badge_service.rb
> +class BadgeService
По данному названию не понятно, что этот сервис делает. Нужно более говорящее название

2021-03-18 09:53 UTC, the-action-man commented on app/services/badge_service.rb
> +class BadgeService
Renamed to BadgeDistributorService

2021-03-18 10:59 UTC, the-action-man commented on app/services/badge_service.rb
> +    end
Счетчиком я считаю для фичи задания "Пользователь может получать один и тот же бэйдж более одного раза".
Что именно  значит "придерживался rails way" в даннном контексте?

2021-03-18 11:14 UTC, the-action-man commented on app/views/badges/index.html.erb
> +  </tr>
done

2021-03-18 11:14 UTC, the-action-man commented on app/views/admin/badges/index.html.erb
> +</table>
done

2021-03-18 11:52 UTC, the-action-man commented on app/specifications/badges/all_from_category.rb
> +    end
I use `(test_passages.keys - test_ids).size.zero?`

2021-03-21 14:18 UTC, the-action-man commented on app/models/badge.rb
> +  validates :rule_type, inclusion: { in: BadgeService.validate_values,
done

2021-03-21 14:18 UTC, the-action-man commented on app/services/badge_service.rb
> +  end
method is removed

2021-03-21 14:20 UTC, the-action-man commented on app/services/badge_service.rb
> +  end
1
для переводов все равно нужен. я не нашел что бы автоматом рэилс искал переводы. Везед на форумах предлагают решение подобное моему
2
moved to Badge

2021-03-22 06:44 UTC, VidgarVii commented on app/services/badge_service.rb
> +    end
ты используешь промежуточную таблицу м/у юзером и баджей. Значит технически кол-во полученных наград юзера = кол-во записей в этой промежуточной таблицы. И для этого уже есть оператор COUNT.
Счётчик есть смысл добавлять, если записей в таблице большое кол-во.

2021-03-22 06:53 UTC, VidgarVii commented on app/services/badge_service.rb
> +  end
конечно есть решение. Похожее на STI
Пример
```
activerecord:
    attributes:
      user/role: # You need to nest the values under model_name/attribute_name
        coordinator: Coordenador
        teacher: Professor


User.human_attribute_name("role.#{@user.role}")
```

2021-03-22 06:59 UTC, VidgarVii commented on app/models/badge.rb
> +end
модель ни чего не знает про локализацию

2021-03-22 06:59 UTC, VidgarVii commented on app/models/test.rb
> +        end)
scope должен быть максимально простым. Иначе клади код в метод класса

2021-03-22 09:15 UTC, the-action-man commented on app/models/test.rb
> +        end)
перенес

2021-03-22 10:34 UTC, merged