Part 18 feature 2 timer
the-action-man/tn-test-guru pull request #33
Opened 2021-04-11 00:05 UTC by the-action-man

<img width="807" alt="изображение" src="https://user-images.githubusercontent.com/49880822/114287819-c5c67900-9a72-11eb-9bfe-e6f2b006eca4.png">

2021-04-12 05:48 UTC, VidgarVii requested changes

2021-04-12 05:48 UTC, VidgarVii commented on app/models/test_passage.rb
> +    created_at + test.timer.minutes < Time.now
всегдя учитывай часовой пояс. используй Time.current

2021-04-12 05:48 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +
проверку таймера лучше сделать в методе `completed?` или эту логику поместить в `accept!`
второй вариант мне даже больше нравится по следующим причинам:
- потому что `completed?` - это метод проверки, а `accept!` как раз метод, в котором действия с объектом и должны происходить (я про название и назначение обоих методов)
- именно этот метод запускается первым при сабмите формы, который произойдет либо по истечению таймера, либо по нажатию кнопки пользователем
- собственно именно в "аксепт" проверяется результат сабмита формы и устанавливается следующий вопрос, поэтому логично время (как еще одну проверку успешности) проверять там
- ну и преждевременное завершение теста (текущий вопрос в нил + нужный флаг в атрибут "завершен вовремя"), можно добавить тут же

в итоге: проверяешь таймер в модели, если истек - ставишь нужный флаг и завершаешь тест, контроллер чистый, вся "логика проверки корректности ответа и завершенности теста" сосредоточена в одном методе модели

2021-04-12 05:48 UTC, VidgarVii commented on app/assets/javascripts/test_passages/timer.js
> +  window.location.replace("/test_passages/" + current_test_passage_id + "/result");
безопасней и лучше просто сабмитеть форму. На сервере у тебя уже есть код, который отправляет на страницу результатов. Надо только добавить логику таймера при обновлении объекта test_passage. Об этом ниже

2021-05-24 20:41 UTC, the-action-man commented on app/models/test_passage.rb
> +    created_at + test.timer.minutes < Time.now
done

2021-05-24 22:32 UTC, the-action-man commented on app/assets/javascripts/test_passages/timer.js
> +  window.location.replace("/test_passages/" + current_test_passage_id + "/result");
i use
```
function redirectionHandler() {
  window.next.click();
}
```

2021-06-13 11:09 UTC, the-action-man commented on app/controllers/test_passages_controller.rb
> +
done

2021-06-14 13:18 UTC, merged